import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] });
import Providers from './providers';
import Header from '@/components/main/header';
import Footer from '@/components/main/footer';
import { parseUiLanguage } from '@/lib/i18n/language-cookie';
import { UI_LANG_STORAGE_KEY } from '@/lib/i18n/resources';
import { getAppSession } from '@/lib/auth/app-session';
export const metadata: Metadata = {
  title: 'Foodluk',
  description: 'Generated by Foodluk',
  icons: {
    icon: '/Logo.png',
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const initialLanguage = parseUiLanguage(
    cookieStore.get(UI_LANG_STORAGE_KEY)?.value
  );
  const session = await getAppSession();

  return (
    <html lang={initialLanguage} className="dark" style={{ colorScheme: 'dark' }}>
      <body className={inter.className}>
        <Providers initialLanguage={initialLanguage} session={session}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
